apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend1-pvc-static-files
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: fast-good-for-db